### ISSUE TITLE
[question about jasper] why jit cannot support masked conv?

### ISSUE THREAD

**Issue by songtaoshi** [NVIDIA/DeepLearningExamples#678] opened 2020-09-08 11:35 UTC
Hi, I am doubtful **WHY** the **masked conv** is not supported with the **torchscript** the jasper. 

I see the note in the inference.py. 
```python
    if args.use_conv_mask and args.export_model:
        print('WARNING: Masked convs currently not supported for TorchScript. Disabling.')
        jasper_model_definition['encoder']['convmask'] = False
```

Is it because there has to be a **tensor size indexing generating python values** in the procedure of mask generation?

```python
        if self.use_conv_mask:
            x, lens = inp
            max_len = x.size(2)
            idxs = torch.arange(max_len).to(lens.dtype).to(lens.device).expand(len(lens), max_len)
            mask = idxs >= lens.unsqueeze(1)
```

If it is so, are there any solutions to solving this problem?  
Since I have trained the masked conv in a large dataset for a long time.

**Comment by alancucki** [comment] 2020-10-07 22:00
Hi @songtaoshi ,
the issue is related to the way TorchScript handles input parameters - with masked convs enabled, the inputs are being passed as tuples, which is incompatible with TS.
This will be fixed in the upcoming update. And don't worry - old checkpoints will load and export to TS just fine.

**Closed** 2021-02-22 14:01 UTC
