### ISSUE TITLE
[DLRM/PyTorch] Training won't work and shows no errors

### ISSUE THREAD

**Issue by cmisale** [NVIDIA/DeepLearningExamples#1155] opened 2022-06-10 13:23 UTC
Related to **DLRM/PyTorch** 

**Describe the bug**
Training script doesn't do anything and does not show any error either. Epoch 0 finishes in 0 seconds.

```
python -m dlrm.scripts.main --mode train --dataset /data/dlrm/binary_dataset/ --amp --cuda_graphs
Not using distributed mode
DLL 2022-06-10 13:08:07.469852 - PARAMETER logtostderr : False  alsologtostderr : False  log_dir :   v : 0  verbosity : 0  logger_levels : {}  stderrthreshold : fatal  showprefixforinfo : True  run_with_pdb : False  pdb_post_mortem : False  pdb : False  run_with_profiling : False  profile_file : None  use_cprofile_for_profiling : True  only_check_args : False  mode : train  seed : 12345  batch_size : 65536  test_batch_size : 65536  lr : 24.0  epochs : 1  max_steps : None  warmup_factor : 0  warmup_steps : 8000  decay_steps : 24000  decay_start_step : 48000  decay_power : 2  decay_end_lr : 0.0  embedding_type : joint_fused  embedding_dim : 128  top_mlp_sizes : [1024, 1024, 512, 256, 1]  bottom_mlp_sizes : [512, 256, 128]  interaction_op : cuda_dot  dataset : /data/dlrm/binary_dataset/  feature_spec : feature_spec.yaml  dataset_type : parametric  shuffle : False  shuffle_batch_order : False  max_table_size : None  hash_indices : False  synthetic_dataset_num_entries : 33554432  synthetic_dataset_table_sizes : ['100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000', '100000']  synthetic_dataset_numerical_features : 13  synthetic_dataset_use_feature_spec : False  load_checkpoint_path : None  save_checkpoint_path : None  log_path : ./log.json  test_freq : None  test_after : 0.0  print_freq : 200  benchmark_warmup_steps : 0  base_device : cuda  amp : True  cuda_graphs : True  inference_benchmark_batch_sizes : [1, 64, 4096]  inference_benchmark_steps : 200  auc_threshold : None  optimized_mlp : True  auc_device : GPU  backend : nccl  bottom_features_ordered : False  freeze_mlps : False  freeze_embeddings : False  Adam_embedding_optimizer : False  Adam_MLP_optimizer : False  ? : False  help : False  helpshort : False  helpfull : False  helpxml : False 
Finished epoch 0 in 0:00:00. 
DLL 2022-06-10 13:08:08.855120 - () best_auc : 0.00000  best_validation_loss : 1000000.0  best_epoch : 0.00  average_train_throughput : nan 
```

**To Reproduce**
Assuming Criteo data is downloaded and preprocessed:
1. `docker build . -t nvidia_dlrm_pyt`
2. `docker run --runtime=nvidia -it --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --security-opt seccomp=unconfined --rm -v /path/to/postprocessed/data:/data nvidia_dlrm_pyt bash`
3. `export DGX_VERSION=DGX-A100` 
4. `python -m dlrm.scripts.main --mode train --dataset /data/dlrm/binary_dataset/ --amp --cuda_graphs`

**Expected behavior**
Seeing epoch being printed as shown in the readme

```
Epoch:[0/1] [200/128028]  eta: 1:28:44  loss: 0.1782  step_time: 0.041657  lr: 0.8794
Epoch:[0/1] [400/128028]  eta: 1:25:15  loss: 0.1403  step_time: 0.038504  lr: 1.7544
Epoch:[0/1] [600/128028]  eta: 1:23:56  loss: 0.1384  step_time: 0.038422  lr: 2.6294
Epoch:[0/1] [800/128028]  eta: 1:23:13  loss: 0.1370  step_time: 0.038421  lr: 3.5044
Epoch:[0/1] [1000/128028]  eta: 1:22:45  loss: 0.1362  step_time: 0.038464  lr: 4.3794
Epoch:[0/1] [1200/128028]  eta: 1:22:24  loss: 0.1346  step_time: 0.038455  lr: 5.2544
Epoch:[0/1] [1400/128028]  eta: 1:22:07  loss: 0.1339  step_time: 0.038459  lr: 6.1294
Epoch:[0/1] [1600/128028]  eta: 1:21:52  loss: 0.1320  step_time: 0.038481  lr: 7.0044
Epoch:[0/1] [1800/128028]  eta: 1:21:39  loss: 0.1315  step_time: 0.038482  lr: 7.8794
Epoch:[0/1] [2000/128028]  eta: 1:21:27  loss: 0.1304  step_time: 0.038466  lr: 8.7544
Epoch:[0/1] [2200/128028]  eta: 1:21:15  loss: 0.1305  step_time: 0.038430  lr: 9.6294
```

**Environment**
Please provide at least:
* Container version: nvcr.io/nvidia/pytorch:21.10-py3
* GPUs in the system: 8x NVidia A100 Ampere
* CUDA driver version: 515.48.07
* CUDA version: 11.7

**Comment by tgrel** [comment] 2022-06-13 17:31
Hi @cmisale.

What is the exact hardware you use for this? Are these A100 SXM devices or A100 PCIe devices? 

Also, could you paste the output of `nvidia-smi` from a separate terminal on the same machine about one minute after starting the training? I'd like to see if the GPUs are being utilized or if the system is completely frozen.

**Comment by cmisale** [comment] 2022-06-16 02:15
Hi @tgrel

The devices are A100 SXM.

I wish I could run the test you are asking, but the program terminates quite immediately, I wouldn't have a chance to run nvidia-smi in another terminal.

I am not sure if some data is broken after preprocessing, because it seems to complete just fine.

**Comment by cmisale** [comment] 2022-06-21 15:41
@tgrel,
I needed to rerun the preprocessing on a subset of the data because I didn't have the space to preprocess the entire thing. Spark was failing with "No space left on device" error. 
I ran preprocessing on 10 days only and now the training is working just fine
```
W0621 15:34:16.147310 139674483947264 fused_gather_embedding.py:38] Highly specialized embedding for embedding_dim 128
Epoch:[0/1] [200/28927]  eta: 0:07:50  loss: 0.18096991  step_time: 0.016363  lr: 0.6030
Epoch:[0/1] [400/28927]  eta: 0:07:46  loss: 0.13825765  step_time: 0.016341  lr: 1.2030
Epoch:[0/1] [600/28927]  eta: 0:07:43  loss: 0.13659638  step_time: 0.016349  lr: 1.8030
Epoch:[0/1] [800/28927]  eta: 0:07:40  loss: 0.13549563  step_time: 0.016381  lr: 2.4030
Epoch:[0/1] [1000/28927]  eta: 0:07:47  loss: 0.13489304  step_time: 0.018302  lr: 3.0030
Epoch:[0/1] [1200/28927]  eta: 0:07:42  loss: 0.13412027  step_time: 0.016299  lr: 3.6030
Epoch:[0/1] [1400/28927]  eta: 0:07:37  loss: 0.13309205  step_time: 0.016267  lr: 4.2030
Epoch:[0/1] [1600/28927]  eta: 0:07:32  loss: 0.13171147  step_time: 0.016304  lr: 4.8030
....
```

The output for `ls -ltrash` is the following (just for completeness)

```
total 20K
   0 drwxrwxrwx 7 root root  120 Jun 20 22:25 ..
8.0K -rw-r--r-- 1 root root 7.1K Jun 20 22:33 feature_spec.yaml
4.0K drwxr-xr-x 2 root root 4.0K Jun 20 22:33 test
4.0K drwxr-xr-x 2 root root 4.0K Jun 20 22:33 train
4.0K drwxr-xr-x 2 root root 4.0K Jun 20 22:38 validation
   0 drwxr-xr-x 5 root root   94 Jun 20 22:39 .
```

I am not sure what went wrong with the entire dataset.

**Comment by tgrel** [comment] 2022-06-24 10:25
I'm glad to hear the issue is resolved. Closing.

**Closed by tgrel** 2022-06-24 10:25 UTC
Labels: bug
