### ISSUE TITLE
[BERT/PyTorch] Error while running pretraining on BERT

### ISSUE THREAD

**Issue by roclark** [NVIDIA/DeepLearningExamples#864] opened 2021-03-09 19:59 UTC
Related to **BERT/PyTorch** 

**Describe the bug**
While running the `run_pretraining.sh` script for BERT with PyTorch, an error is thrown while it attempts to load models in Python. The default parameters for the script point to the `/workspace/bert/results/checkpoints` directory to read all model files from, but if the README is followed as written, this directory will be empty. Assuming this is looking for the checkpoint file that was optionally downloaded from a previous step (which, I don't see anything in the README discussing how to run without the checkpoint despite it being shown as optional, but that's a different issue), that is placed by default in the `/workspace/bert/checkpoints` directory. Assuming the checkpoint file from the previous step is the correct one to use, I tried copying it to the `/workspace/bert/results/checkpoints` directory and running again which made it past the error below, but ran into another error quickly after which may or may not be related.

Error below:

```
device: cuda:1 n_gpu: 1, distributed training: True, 16-bits training: True
device: cuda:0 n_gpu: 1, distributed training: True, 16-bits training: True
DLL 2021-03-09 19:14:23.216951 - PARAMETER Config : ["Namespace(allreduce_post_accumulation=True, allreduce_post_accumulation_fp16=True, amp=False, bert_model='bert-large-uncased', checkpoint_activations=False, config_file='bert_config.json', disable_progress_bar=False, do_train=True, fp16=True, gradient_accumulation_steps=512, init_checkpoint=None, init_loss_scale=1048576, input_dir='/workspace/bert/data/hdf5_lower_case_1_seq_len_512_max_pred_80_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_shard_1472_test_split_10/books_wiki_en_corpus/training/', json_summary='/workspace/bert/results/dllogger.json', learning_rate=0.004, local_rank=0, log_freq=1.0, loss_scale=0.0, max_predictions_per_seq=80, max_seq_length=512, max_steps=1563.0, n_gpu=1, num_steps_per_checkpoint=200, num_train_epochs=3.0, output_dir='/workspace/bert/results/checkpoints', phase1_end_step=7038, phase2=True, resume_from_checkpoint=True, resume_step=-1, seed=12439, skip_checkpoint=False, steps_this_run=1563.0, train_batch_size=8, use_env=False, warmup_proportion=0.128)"] 
/workspace/bert/results/checkpoints  # <--- Line I manually added to view the output directory
[]  # <--- Line I manually added to view the list of models
Traceback (most recent call last):
  File "/workspace/bert/run_pretraining.py", line 680, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/workspace/bert/run_pretraining.py", line 508, in main
    model, optimizer, lr_scheduler, checkpoint, global_step, criterion = prepare_model_and_optimizer(args, device)
  File "/workspace/bert/run_pretraining.py", line 361, in prepare_model_and_optimizer
    args.resume_step = max([int(x.split('.pt')[0].split('_')[1].strip()) for x in model_names])
ValueError: max() arg is an empty sequence
/workspace/bert/results/checkpoints  # <--- Line I manually added to view the output directory
[]  # <--- Line I manually added to view the list of models
Traceback (most recent call last):
  File "/workspace/bert/run_pretraining.py", line 680, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/workspace/bert/run_pretraining.py", line 508, in main
    model, optimizer, lr_scheduler, checkpoint, global_step, criterion = prepare_model_and_optimizer(args, device)
  File "/workspace/bert/run_pretraining.py", line 361, in prepare_model_and_optimizer
    args.resume_step = max([int(x.split('.pt')[0].split('_')[1].strip()) for x in model_names])
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', '/workspace/bert/run_pretraining.py', '--local_rank=1', '--input_dir=/workspace/bert/data/hdf5_lower_case_1_seq_len_512_max_pred_80_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_shard_1472_test_split_10/books_wiki_en_corpus/training/', '--output_dir=/workspace/bert/results/checkpoints', '--config_file=bert_config.json', '--bert_model=bert-large-uncased', '--train_batch_size=4096', '--max_seq_length=512', '--max_predictions_per_seq=80', '--max_steps=1563', '--warmup_proportion=0.128', '--num_steps_per_checkpoint=200', '--learning_rate=4e-3', '--seed=12439', '--fp16', '--gradient_accumulation_steps=512', '--allreduce_post_accumulation', '--allreduce_post_accumulation_fp16', '--do_train', '--phase2', '--resume_from_checkpoint', '--phase1_end_step=7038', '--json-summary', '/workspace/bert/results/dllogger.json']' returned non-zero exit status 1.
```

This raises the following questions/issues:
1. Is the checkpoint downloaded from NGC in step 2 of the BERT README the checkpoint that is used for the `run_pretraining.sh` script?
  a. If so, should step 2 be updated to save the checkpoint to `BERT/results/checkpoints` directory outside of the container?
  b. If not, which checkpoint file is expected here?
2. With the pretrained checkpoints being listed as optional, there should be steps to indicate what's needed to run without them so the code can be replicated.

**To Reproduce**
1. Configure a new machine (or isolated repo locally) *without any data/checkpoints downloaded.*
2. Download the pretrained checkpoint from [NGC](https://ngc.nvidia.com/catalog/models/nvidia:bert_pyt_ckpt_large_pretraining_amp_lamb/files) and save it to the `DeepLearningExamples/PyTorch/LanguageModeling/BERT/checkpoints/` directory.
3. Build the latest BERT container according to the steps in the [PyTorch BERT README](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/README.md).
4. Launch the container using `bash scripts/docker/launch.sh`.
5. Download and process the dataset with `/workspace/bert/data/create_datasets_from_start.sh` inside the container.
6. Run the pretraining script with `bash scripts/run_pretraining.sh` inside the container. If no other directories were touched outside of what's listed in the README, this will throw the error above.

**Expected behavior**
I either expect the `run_pretraining.sh` script to continue without errors, or steps in the README to indicate how to run without the pretrained model.

**Environment**
Please provide at least:
* Container version: The built `bert` container from the README (doesn't have any tags or specifics).
* GPUs in the system: 2x Quadro RTX 8000 48GB
* CUDA driver version: 460.32.03

**Comment by sharathts** [comment] 2021-03-16 22:23
Resolved internally, not a bug.

**Closed by sharathts** 2021-03-16 22:23 UTC
Labels: bug
