### ISSUE TITLE
[FastTransformer v3.1/TensorFlow] Get CUBLAS_STATUS_INTERNAL_ERROR when run tensorflow/gpt2-sample.py

### ISSUE THREAD

**Issue by aoyulong** [NVIDIA/DeepLearningExamples#829] opened 2021-02-10 09:49 UTC
Related to **FastTransformer v3.1/TensorFlow/GPT-2** 

**Describe the bug**
If I run `./bin/decoding_gemm 4 1 12 64 50257 32 768 0` before `python tensorflow/gpt2_sample.py`, I got
`Internal: [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_INTERNAL_ERROR FasterTransformer/fastertransformer/cuda/open_decoder.cu:1708`.
However, If I don't run  `./bin/decoding_gemm 4 1 12 64 50257 32 768 0` before `python tensorflow/gpt2_sample.py` (use the default gemm), everything is OK.

**To Reproduce**
1. `nvidia-docker run -it  -v local_dir:container_dir nvcr.io/nvidia/tensorflow:19.06-py3 bash`
2. `cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/usr/local/lib/python3.5/dist-packages/tensorflow ..`
3. `make`
4. `./bin/decoding_gemm 4 1 12 64 50257 32 768 0`
5. `python tensorflow/gpt2_sample.py`

**Expected behavior**
There should be no error.

**Environment**
Please provide at least:
* Container version: nvcr.io/nvidia/tensorflow:19.06-py3
* GPUs in the system: 8x Tesla V100-32GB
* CUDA driver version: 435.21

**Comment by byshiue** [comment] 2021-02-10 10:33
The reason should be using wrong gemm algo. 
Do you run the tensorflow sample code with "--batch_size=4"? This gemm test is used for such case.

**Comment by aoyulong** [comment] 2021-02-15 03:18
I try to run it with `python tensorflow/gpt2_sample.py --batch_size=4 --length=32 --top_k=4 --top_k=4 --data_type=fp32` and get the same error even without `./bin/decoding_gemm 4 1 12 64 50257 32 768 0`.
![image](https://user-images.githubusercontent.com/3069790/107901657-34a9b900-6f7f-11eb-9a5f-c5c82d62f859.png)

**Comment by byshiue** [comment] 2021-02-18 00:33
Hi. I cannot reproduce your problem on image `nvcr.io/nvidia/tensorflow:19.07-py3` and `nvcr.io/nvidia/tensorflow:20.12-tf1-py3`. The version of cmake and TensorFlow in `nvcr.io/nvidia/tensorflow:19.06-py3` are older than we test. Can you try these newer images?

**Comment by aoyulong** [comment] 2021-02-18 06:30
@byshiue I try the `nvcr.io/nvidia/tensorflow:19.07-py3` image but get the same error. What is the version of your CUDA Driver? Mine is 435.21.

**Comment by byshiue** [comment] 2021-02-18 06:46
driver version: 460.32
cuda version: 11.2

However, it is strange that you only encounter problem on tensorflow sample code, but running c++ sample code successfully because they use same codes to run inference. 

Can you check followings cases:
1. Run under Debug mode. (Modify `-DCMAKE_BUILD_TYPE=Release` to `-DCMAKE_BUILD_TYPE=Debug`)
2. Check the cublas algorithm you use at line 867 of `open_decoder.cu`.

**Comment by aoyulong** [comment] 2021-02-18 07:34
@byshiue I run the code under debug mode and print the algorithm. The results is: 
![image](https://user-images.githubusercontent.com/3069790/108321142-b8bda400-71fe-11eb-87ea-223a0493bf25.png)

**Comment by byshiue** [comment] 2021-02-18 09:20
1. For the warning `[WARNING] the file dimension does not match with input dim0! ./tmp/model.wpe.csv, dim0=32, i0=32` , it is fine. 
2. You can use newer driver to run older cuda, but you cannot use older driver to run newer cuda. So, it is ok, too.

Can you try to run other samples of c and tensorflow? Like `encoder_sample`, `decoding_sample`.
Besides, can you try `19.05` image? I find that the version of cublas of `19.06`  and newer images are 10.2 but not 10.1 althought the version of cuda is 10.1.

**Comment by aoyulong** [comment] 2021-02-18 10:12
@byshiue  After trying 19.05, I also get the same error :). But I can run other encoder_sample and decoding sample of tensorflow in 19.07 and 19.05.

**Comment by byshiue** [comment] 2021-02-18 10:46
It's strange. I have no more ideas. I will check the source codes of ft-gpt again.

**Comment by aoyulong** [comment] 2021-02-18 10:51
> It's strange. I have no more ideas. I will check the source codes of ft-gpt again.

Thanks a lot. I will update my cuda driver and have a try.

**Comment by aoyulong** [comment] 2021-02-18 11:36
@byshiue I test the code on a new version of dirvier 460.32.03 and get the same error. I don't think the driver leads to the problem. The already tested results are summarized as follow:

- Without runing `./bin/decoding_gemm` , the code is OK when batch_size=1. But with running `./bin/decoding_gemm`, the error occurs when batch_size=1 and batch_size=4.
- The gpt2 c++ samples is OK.
- Other tensorflow samples is OK.

I will appreciate if you can describe the compiling process and running command when you run the `tensorflow/gpt2_sample.py` in detail. I may run the code in a wrong way. Besides, are there specical options when run the docker image?

**Comment by byshiue** [comment] 2021-02-18 23:20
There is no special option or command. The commands to compile the codes are described in `README.md`. 
You can try to check all inputs of the cublasGemm under c++ and tensorflow. I will also continue trying to reproduce the problem.

**Comment by byshiue** [comment] 2021-02-19 01:31
There are some useful tool functions. 
1. `print_first_k` in `cuda_kernels.h`: You can use it to check first and last some values of inputs, weights.
2. `print_to_file` in `utils/common.h`: You can dump full inputs, weights into a file and compare them. You can use python to write a simple tool to compare values of two files.

**Comment by aoyulong** [comment] 2021-02-19 02:57
Thanks for your suggestion and I will try to locate the error's cause.

**Comment by aoyulong** [comment] 2021-02-19 09:35
@byshiue Hi, everything is OK when I run the script as`CUDA_VISIBLE_DEVICES=0 python tensorflow/gpt2_sample.py --batch_size=4 --length=32 --top_k=4 --top_p=0.6 --data_type=fp32`. I don't change anything and just add **CUDA_VISIBLE_DEVICES=0**. So strange!

**Comment by byshiue** [comment] 2021-02-19 11:09
Great! Then I close this bug. I will continue the check why this problem happen, thanks.

**Closed by byshiue** 2021-02-19 11:09 UTC
Labels: bug

**Comment by byshiue** [comment] 2021-02-22 10:11
@aoyulong Hi, I find another method to solve this problem, you can try it.
Please add `sess.run(tf.global_variables_initializer())` after https://github.com/NVIDIA/DeepLearningExamples/blob/master/FasterTransformer/v3.1/sample/tensorflow/gpt2_sample.py#L109.
