### ISSUE TITLE
FasterTransformer failed to run FP16 mode on Tesla P100

### ISSUE THREAD

**Issue by 372046933** [NVIDIA/DeepLearningExamples#601] opened 2020-07-13 13:02 UTC
Related to **Model/Framework(s)** 
* FasterTransformer

**Describe the bug**
```tensorflow: python.framework.errors impl.NotFoundError: /lib/libtffastertransformer.so:undefinedsymbol: _ZN10tensorflow7functor27OpenNmtTransformerOpFunctorlN5Eigen9GpuDeviceENS2_4halfEE7ComputeEPNS_ 15OpKernelContextEN17fastertransformer16EncoderlnitParamI6_halfEEPNS8_25OpenNmtEncoderTransformerlNS8_ 31OpenNmtEncoderTransformerTraitsILNS8 13.OperationTypeE1ENS8 4cuda22OpenMultiHeadAttentionEEEE```
**To Reproduce**
```bash
cmake -DSM=60 -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/usr/local/lib/python2.7/dist-packages/tensorflow .. # Tensorflow mode

./bin/encoder_gemm 1 32 12 64 1
./bin/encoder_sample 1 12 32 12 64 1
python encoder_sample.py \
        --batch_size 1 \
        --seq_len 32 \
        --head_number 12 \
        --size_per_head 64 \
        --num_layer 12 \
        --data_type fp16 \
        --test_time 1
```
I also tested the same code on Tesla V100, changed DSM to `70`, FP16 works. 

**Expected behavior**
FP16 `encoder_sampy.py' should run correctly.
**Environment**
Please provide at least:
* Container version (nvcr.io/nvidia/tensorflow:19.07-py2):
* GPUs in the system: (Tesla P100-PCIE-16GB):
* CUDA driver version (418.87.00):

**Comment by byshiue** [comment] 2020-07-13 23:52
First, I guess you use the TensorFlow of TensorFlow-py2 container but not the pytorch-py2 container.
Second, I cannot reproduce your problem.
From your log and description, it seems that you can run the FT on cpp successfully, but cannot run on the TensorFlow. 
The problem may be caused by the environment and the progress of building project. 
I will try to reproduce this problem, and please provide more information if you can.

**Comment by 372046933** [comment] 2020-07-14 07:05
@byshiue . Thanks for your reply. I removed the `build` directory and rebuild the project. Now `encoder_sample.py` runs normally. Still within the same container. I made a mistake in the first post. The container image is `nvcr.io/nvidia/tensorflow:19.07-py2`. I guess that the cause is some modification in the CUDA code, but I cannot reproduce it now.

**Comment by byshiue** [comment] 2020-07-17 10:47
Close this commit because the problem is solved.

**Closed by byshiue** 2020-07-17 10:47 UTC
Labels: bug
