### ISSUE TITLE
The data_download.sh script doesn't process wikipedia

### ISSUE THREAD

**Issue by yaroslavvb** [NVIDIA/DeepLearningExamples#33] opened 2019-04-24 22:27 UTC
Here are the files I see after going through data download instructions in https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT

The wikipedia directory seems to be missing files. Here's what I see after running `data_download.sh` which takes about 20 hours

```
4.0K    ./data/wikipedia_corpus/intermediate_files
16G     ./data/wikipedia_corpus/download
4.0K    ./data/wikipedia_corpus/final_text_files_sharded
67G     ./data/wikipedia_corpus/raw_data
13G     ./data/wikipedia_corpus/extracted_articles/AA
13G     ./data/wikipedia_corpus/extracted_articles
4.0K    ./data/wikipedia_corpus/final_text_file_single
4.0K    ./data/wikipedia_corpus/final_tfrecords_sharded
95G     ./data/wikipedia_corpus
5.2G    ./data/bookcorpus/intermediate_files
5.3G    ./data/bookcorpus/download
5.2G    ./data/bookcorpus/final_text_files_sharded
5.2G    ./data/bookcorpus/final_text_file_single
52G     ./data/bookcorpus/final_tfrecords_sharded
72G     ./data/bookcorpus
45M     ./data/squad/v2.0
34M     ./data/squad/v1.1
78M     ./data/squad
417M    ./data/pretrained_models_google/cased_L-12_H-768_A-12
394M    ./data/pretrained_models_google/chinese_L-12_H-768_A-12
643M    ./data/pretrained_models_google/multilingual_L-12_H-768_A-12
422M    ./data/pretrained_models_google/uncased_L-12_H-768_A-12
1.3G    ./data/pretrained_models_google/uncased_L-24_H-1024_A-16
684M    ./data/pretrained_models_google/multi_cased_L-12_H-768_A-12
1.3G    ./data/pretrained_models_google/cased_L-24_H-1024_A-16
9.7G    ./data/pretrained_models_google
177G    ./data
16K     ./__pycache__
12K     ./scripts/docker
44K     ./scripts
177G    .
```

Note that it only extracts `AA` of the wikipedia and the final sharded directories are empty.
Book corpus worked fine

**Comment by nvcforster** [comment] 2019-04-25 19:14
This seems to be an intermittent issue with WikiExtractor when more threads are requested than are on the system it is being run on. Reducing thread count in the script and rerunning typically solves the problem. We will try to reproduce this on our end in the meantime. Please let us know if this problem persists.

**Comment by nvpstr** [comment] 2019-06-06 14:07
Closing - no answer for a long time.

**Closed by nvpstr** 2019-06-06 14:07 UTC
