### ISSUE TITLE
Preprocessing custom dataset NCF

### ISSUE THREAD

**Issue by taquanghung1705199** [NVIDIA/DeepLearningExamples#987] opened 2021-08-16 02:54 UTC
I have a problem relate to custom dataset. When training with NCF
Follow: https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/NCF#dataset-guidelines

with movielens-1m dataset
<pre>test_ratings.shape: torch.Size([<b>6040</b>, 2])
test_negs.shape: torch.Size([<b>6040</b>, 100])</pre>

with movielens-20m dataset
<pre>test_ratings.shape: torch.Size([<b>138493</b>, 2])
test_negs.shape: torch.Size([<b>138493</b>, 100])</pre>

But when I preprocessing with my custom dataset (by convert.py and have slightly adjusted to fit my dataset):
<pre>test_ratings.shape: torch.Size([<b>54979</b>, 2])
test_negs.shape: torch.Size([<b>122071</b>, 100])</pre>

Because sizes of tensors is not match so I cant training. This is error:
<pre>root@09c81abf62b4:/workspace/recommendation# python -m torch.distributed.launch --nproc_per_node=1 --use_env ncf.py --data /data/fhs/
DLL 2021-08-16 02:42:15.324046 - PARAMETER data : /data/fhs/  epochs : 30  batch_size : 32768  valid_batch_size : 1024  factors : 64  layers : [256, 256, 128, 64]  negative_samples : 4  learning_rate : 0.0045  topk : 10  seed : None  threshold : 1.0  beta1 : 0.25  beta2 : 0.5  eps : 1e-08  dropout : 0.5  checkpoint_dir :   load_checkpoint_path : None  mode : train  grads_accumulated : 1  amp : False  log_path : log.json  world_size : 1  distributed : False  local_rank : 0 
Traceback (most recent call last):
  File &quot;ncf.py&quot;, line 332, in &lt;module&gt;
    main()
  File &quot;ncf.py&quot;, line 196, in main
    test_users, test_items, dup_mask, real_indices = dataloading.create_test_data(test_ratings, test_negs, args)
  File &quot;/workspace/recommendation/dataloading.py&quot;, line 42, in create_test_data
    test_items = torch.cat((test_negs, test_pos), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 0. Got <b>54979</b> and <b>122071</b>
Traceback (most recent call last):
  File &quot;/opt/conda/lib/python3.6/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/opt/conda/lib/python3.6/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py&quot;, line 263, in &lt;module&gt;
    main()
  File &quot;/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py&quot;, line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command &apos;[&apos;/opt/conda/bin/python&apos;, &apos;-u&apos;, &apos;ncf.py&apos;, &apos;--data&apos;, &apos;/data/fhs/&apos;]&apos; returned non-zero exit status 1.
</pre>

Does anyone know the cause and how to fix it? 
Plz help me!

**Comment by tgrel** [comment] 2021-08-18 15:41
Hi @taquanghung1705199,

Unfortunately it's going to be difficult to fix this without the input data. One hypothesis is that there might be a bug in the negative sampling procedure for the test dataset. Another is that something went wrong with reading and filtering the test positive examples. The code that handles both those things is here: https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Recommendation/NCF/convert.py#L111

You should be able to go through it line by line and find the root cause of the problem by checking the shapes of the tensors.

Good luck!
Tomasz

**Comment by tgrel** [comment] 2021-08-23 08:27
Closing.

**Closed by tgrel** 2021-08-23 08:27 UTC
